name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SECRET_HOST}}
          username: ${{secrets.SECRET_USERNAME}}
          key: ${{secrets.PRIVATE_DEPLOY_KEY}}
          script: echo hello world > hello.txt
