name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SECRET_HOST}}
          username: ${{secrets.SECRET_USERNAME}}
          password: ${{secrets.SECRET_PASSWORD}}
          script: echo hello world > hello.txt
